name: Build and push packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: 'flowfuse/github-actions-workflows/.github/workflows/build_node_package.yml@feat-build-node-multiple-node-versions'
    with:
      run_tests: true
      # node: '[
      #         {"version": "14", "test": true, "lint": false},
      #         {"version": "18", "test": true, "lint": true}
      #         ]'
      # node_version: '[14, 16, 18, 20]'

  publish:
    needs: build
    if: |
      ( github.event_name == 'push' && github.ref == 'refs/heads/main' ) ||
      ( github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' )
    uses: 'flowfuse/github-actions-workflows/.github/workflows/publish_node_package.yml@v0.1.0'
    with:
      package_name: nr-project-nodes
      publish_package: true
    secrets:
      npm_registry_token: ${{ secrets.NPM_PUBLISH_TOKEN }}

  dispatch_nr_launcher:
    name: Dispatch nr-launcher package build
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_BOT_APP_ID }}
          private_key: ${{ secrets.GH_BOT_APP_KEY }}
      - name: Trigger nr-launcher package build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: publish.yml
          repo: flowfuse/nr-launcher
          ref: main
          token: ${{ steps.generate_token.outputs.token }}
          inputs: '{"nr_project_nodes_ref": "${{ github.ref }}", "nr_project_nodes_release_name": "${{ needs.publish.outputs.release_name }}"}'
